version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###

###> Typesense ###
  typesence:
    image: typesense/typesense:0.22.2
    environment:
      TYPESENCE_DATA_DIR: /data
      TYPESENCE_API_KEY: xyz
    volumes:
      - /tmp/typesense-server-data:/data
    ports:
      - 8108:8108
    restart: "no"
###> Typesense ###
    


